// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Order struct {
	ID        int64     `json:"id"`
	NameID    int64     `json:"nameID"`
	IDUnionop int64     `json:"idUnionop"`
	Total     float64   `json:"total"`
	Subtotal  float64   `json:"subtotal"`
	Taxes     string    `json:"taxes"`
	Paid      string    `json:"paid"`
	CreatedAt time.Time `json:"createdAt"`
}

type Payment struct {
	ID        int64     `json:"id"`
	Type      string    `json:"type"`
	TxnID     string    `json:"txnID"`
	Total     float64   `json:"total"`
	CreatedAt time.Time `json:"createdAt"`
}

type Shipping struct {
	ID      int64   `json:"id"`
	Address string  `json:"address"`
	City    string  `json:"city"`
	State   string  `json:"state"`
	Country string  `json:"country"`
	Cost    float64 `json:"cost"`
}

type UnionO struct {
	IDShipping int64 `json:"idShipping"`
}

type UnionOP struct {
	IDPayment int64 `json:"idPayment"`
}

type User struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	LastName string `json:"lastName"`
	GobID    string `json:"gobID"`
	Email    string `json:"email"`
	Company  string `json:"company"`
}
